// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package crsf

import (
	"errors"
	"fmt"
)

const (
	// AddressTypeFlightController is a AddressType of type FlightController.
	// Most should have this address
	AddressTypeFlightController AddressType = iota + 200
	// AddressTypeRadioTransmitter is a AddressType of type RadioTransmitter.
	AddressTypeRadioTransmitter AddressType = iota + 233
	// AddressTypeReceiver is a AddressType of type Receiver.
	AddressTypeReceiver AddressType = iota + 234
	// AddressTypeTransmitter is a AddressType of type Transmitter.
	// channels should have this address
	AddressTypeTransmitter AddressType = iota + 235
)

var ErrInvalidAddressType = errors.New("not a valid AddressType")

const _AddressTypeName = "FlightControllerRadioTransmitterReceiverTransmitter"

var _AddressTypeMap = map[AddressType]string{
	AddressTypeFlightController: _AddressTypeName[0:16],
	AddressTypeRadioTransmitter: _AddressTypeName[16:32],
	AddressTypeReceiver:         _AddressTypeName[32:40],
	AddressTypeTransmitter:      _AddressTypeName[40:51],
}

// String implements the Stringer interface.
func (x AddressType) String() string {
	if str, ok := _AddressTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("AddressType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AddressType) IsValid() bool {
	_, ok := _AddressTypeMap[x]
	return ok
}

var _AddressTypeValue = map[string]AddressType{
	_AddressTypeName[0:16]:  AddressTypeFlightController,
	_AddressTypeName[16:32]: AddressTypeRadioTransmitter,
	_AddressTypeName[32:40]: AddressTypeReceiver,
	_AddressTypeName[40:51]: AddressTypeTransmitter,
}

// ParseAddressType attempts to convert a string to a AddressType.
func ParseAddressType(name string) (AddressType, error) {
	if x, ok := _AddressTypeValue[name]; ok {
		return x, nil
	}
	return AddressType(0), fmt.Errorf("%s is %w", name, ErrInvalidAddressType)
}

const (
	// FrameTypeGPS is a FrameType of type GPS.
	FrameTypeGPS FrameType = iota + 2
	// FrameTypeVario is a FrameType of type Vario.
	FrameTypeVario FrameType = iota + 6
	// FrameTypeBatterySensor is a FrameType of type BatterySensor.
	FrameTypeBatterySensor
	// FrameTypeBarometer is a FrameType of type Barometer.
	FrameTypeBarometer
	// FrameTypeLinkStats is a FrameType of type LinkStats.
	FrameTypeLinkStats FrameType = iota + 16
	// FrameTypeChannels is a FrameType of type Channels.
	FrameTypeChannels FrameType = iota + 17
	// FrameTypeChannelSubSet is a FrameType of type ChannelSubSet.
	FrameTypeChannelSubSet
	// FrameTypeLinkRx is a FrameType of type LinkRx.
	FrameTypeLinkRx FrameType = iota + 21
	// FrameTypeLinkTx is a FrameType of type LinkTx.
	FrameTypeLinkTx
	// FrameTypeAttitude is a FrameType of type Attitude.
	FrameTypeAttitude
	// FrameTypeFlightMode is a FrameType of type FlightMode.
	FrameTypeFlightMode FrameType = iota + 23
)

var ErrInvalidFrameType = errors.New("not a valid FrameType")

const _FrameTypeName = "GPSVarioBatterySensorBarometerLinkStatsChannelsChannelSubSetLinkRxLinkTxAttitudeFlightMode"

var _FrameTypeMap = map[FrameType]string{
	FrameTypeGPS:           _FrameTypeName[0:3],
	FrameTypeVario:         _FrameTypeName[3:8],
	FrameTypeBatterySensor: _FrameTypeName[8:21],
	FrameTypeBarometer:     _FrameTypeName[21:30],
	FrameTypeLinkStats:     _FrameTypeName[30:39],
	FrameTypeChannels:      _FrameTypeName[39:47],
	FrameTypeChannelSubSet: _FrameTypeName[47:60],
	FrameTypeLinkRx:        _FrameTypeName[60:66],
	FrameTypeLinkTx:        _FrameTypeName[66:72],
	FrameTypeAttitude:      _FrameTypeName[72:80],
	FrameTypeFlightMode:    _FrameTypeName[80:90],
}

// String implements the Stringer interface.
func (x FrameType) String() string {
	if str, ok := _FrameTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("FrameType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x FrameType) IsValid() bool {
	_, ok := _FrameTypeMap[x]
	return ok
}

var _FrameTypeValue = map[string]FrameType{
	_FrameTypeName[0:3]:   FrameTypeGPS,
	_FrameTypeName[3:8]:   FrameTypeVario,
	_FrameTypeName[8:21]:  FrameTypeBatterySensor,
	_FrameTypeName[21:30]: FrameTypeBarometer,
	_FrameTypeName[30:39]: FrameTypeLinkStats,
	_FrameTypeName[39:47]: FrameTypeChannels,
	_FrameTypeName[47:60]: FrameTypeChannelSubSet,
	_FrameTypeName[60:66]: FrameTypeLinkRx,
	_FrameTypeName[66:72]: FrameTypeLinkTx,
	_FrameTypeName[72:80]: FrameTypeAttitude,
	_FrameTypeName[80:90]: FrameTypeFlightMode,
}

// ParseFrameType attempts to convert a string to a FrameType.
func ParseFrameType(name string) (FrameType, error) {
	if x, ok := _FrameTypeValue[name]; ok {
		return x, nil
	}
	return FrameType(0), fmt.Errorf("%s is %w", name, ErrInvalidFrameType)
}
